# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Offsetor
                                 A QGIS plugin
 Calculates points from the offset positions off a base line
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-09-06
        copyright            : (C) 2025 by Alexander von Lunen
        email                : avl1@gmx.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Offsetor class from file Offsetor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .offsetor import Offsetor
    return Offsetor(iface)
